# Generated by Django 3.0.5 on 2020-06-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='test_user',
        ),
    ]
